# -*- coding: utf-8 -*-
"""test3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vGRzhGJsuRIqVCSyLUUh9BkzcDrUougB
"""

!apt-get install -y xvfb swig cmake
!pip install pyvirtualdisplay
!pip install stable-baselines3==2.1.0
!pip install gymnasium[box2d] imageio
#!pip install "gymnasium[box2d]==0.29.1"
#!pip install numpy==1.26.4 --force-reinstall
#!pip install -U "gymnasium[box2d]"
#!pip install imageio

from google.colab import drive
drive.flush_and_unmount()
print('Drive unmounted')
drive.mount('/content/MyDrive')
print('Drive mounted')

#!cp ./logs/ppo_car_racing.zip /content/drive/MyDrive/

!ls /content/MyDrive

from google.colab import drive
drive.mount('/content/drive')
!cp /content/drive/MyDrive/ppo_car_racing.zip /content/drive/MyDrive/

!cp /content/drive/MyDrive/ppo_car_racing.zip /content/drive/MyDrive/ppo_car_racing_copy.zip

!pip install -U gymnasium stable-baselines3

import gymnasium as gym
from stable_baselines3 import PPO

import gymnasium as gym
env = gym.make("CarRacing-v3", render_mode="rgb_array")
print(env.observation_space)
model = PPO("CnnPolicy", env, verbose=1)
model.learn(total_timesteps=100000)
model.save("ppo_car_racing_trained")

!ls -l /content/ppo_car_racing_trained.zip

model.save("/content/drive/MyDrive/ppo_car_racing_trained")

from stable_baselines3.common.evaluation import evaluate_policy

env = gym.make("CarRacing-v3", render_mode="rgb_array")
model = PPO.load("/content/ppo_car_racing_trained.zip", env=env)

mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=10)
print(f"Mean reward: {mean_reward}, Standard deviation: {std_reward}")

import imageio
from stable_baselines3.common.vec_env import DummyVecEnv
env = gym.make("CarRacing-v3", render_mode="rgb_array")
env = DummyVecEnv([lambda: env])

#!pip install --upgrade imageio imageio-ffmpeg

images = []
obs = env.reset()
for i in range(1000):
    action, _ = model.predict(obs)
    obs, reward, done, info = env.step(action)
    images.append(env.render())
    if done:
        break

imageio.mimsave("car_racing_video.mp4", images, fps=30)

imageio.mimsave("car_racing_video.mp4", images, fps=30)

from IPython.display import HTML
HTML("""
<video width="600" height="400" controls>
    <source src="car_racing_video.mp4" type="video/mp4">
    Your browser does not support the video tag.
</video>
""")

import matplotlib.pyplot as plt
plt.imshow(images[0])
plt.show()

from IPython.display import Video
Video("car_racing_video.mp4", embed=True, width=600, height=400, html_attributes="autoplay loop")

from google.colab import files
files.download('car_racing_video.mp4')

env = gym.make("CarRacing-v3", render_mode="rgb_array")
model = PPO.load("ppo_car_racing_trained.zip", env=env)

model.learn(total_timesteps=50000)

env = gym.make("CarRacing-v3", render_mode="rgb_array")
model = PPO.load("ppo_car_racing_trained.zip", env=env)

env = DummyVecEnv([lambda: env])


images = []
obs = env.reset()
for i in range(1000):
    action, _ = model.predict(obs)
    obs, reward, done, info = env.step(action)
    images.append(env.render())
    if done:
        break

imageio.mimsave("car_racing_video_updated.mp4", images, fps=30)

plt.imshow(images[0])
plt.show()

env = gym.make("CarRacing-v3", render_mode="rgb_array")
model = PPO.load("ppo_car_racing_trained.zip", env=env)

from stable_baselines3.common.vec_env import DummyVecEnv
env = DummyVecEnv([lambda: env])

from IPython.display import Video
Video("car_racing_video_updated.mp4", embed=True, width=600, height=400, html_attributes="autoplay loop")

from google.colab import files
files.download('car_racing_video_updated.mp4')

model.learn(total_timesteps=50000)

model.save("ppo_car_racing_trained")

model.save("ppo_car_racing_trained")

env = gym.make("CarRacing-v3", render_mode="rgb_array")
model = PPO.load("ppo_car_racing_trained.zip", env=env)

env = DummyVecEnv([lambda: env])


images = []
obs = env.reset()
for i in range(1000):
    action, _ = model.predict(obs)
    obs, reward, done, info = env.step(action)
    images.append(env.render())
    if done:
        break

imageio.mimsave("car_racing_video_updated2.mp4", images, fps=30)

Video("car_racing_video_updated2.mp4", embed=True, width=600, height=400, html_attributes="autoplay loop")



from google.colab import files
files.download('car_racing_video_updated2.mp4')

!apt-get install -y xvfb swig cmake
!pip install pyvirtualdisplay
!pip install stable-baselines3==2.1.0
!pip install gymnasium[box2d] imageio
#!pip install "gymnasium[box2d]==0.29.1"
#!pip install numpy==1.26.4 --force-reinstall
#!pip install -U "gymnasium[box2d]"
#!pip install imageio

!pip install -U gymnasium stable-baselines3

!pip uninstall -y numpy
!pip install --no-cache-dir numpy

from google.colab import drive
drive.flush_and_unmount()
print('Drive unmounted')
drive.mount('/content/MyDrive')
print('Drive mounted')
# Copy model to Google Drive
#!cp ./logs/ppo_car_racing.zip /content/drive/MyDrive/

from google.colab import drive
drive.mount('/content/drive')
!cp /content/drive/MyDrive/ppo_car_racing.zip /content/drive/MyDrive/

!cp /content/drive/MyDrive/ppo_car_racing.zip /content/drive/MyDrive/ppo_car_racing_copy.zip

!pip install -U gymnasium stable-baselines3

import gymnasium as gym
from stable_baselines3 import PPO

env = gym.make("CarRacing-v3", render_mode="rgb_array")


model = PPO.load("ppo_car_racing_trained_v2", env=env)

model.learn(total_timesteps=100_000)

model.save("ppo_car_racing_trained_v3")

from stable_baselines3.common.vec_env import DummyVecEnv
import imageio
from IPython.display import Video

env = gym.make("CarRacing-v3", render_mode="rgb_array")

model = PPO.load("ppo_car_racing_trained_v3", env=env)

env = DummyVecEnv([lambda: env])

images = []
obs = env.reset()
for i in range(1000):
    action, _ = model.predict(obs)
    obs, reward, done, info = env.step(action)
    images.append(env.render())
    if done:
        break

imageio.mimsave("car_racing_video_updated3.mp4", images, fps=30)


Video("car_racing_video_updated3.mp4", embed=True, width=600, height=400, html_attributes="autoplay loop")

from google.colab import files

files.download('car_racing_video_updated3.mp4')

env = gym.make("CarRacing-v3", render_mode="rgb_array")

model = PPO.load("ppo_car_racing_trained_v3", env=env)

model.learn(total_timesteps=200_000)

model.save("ppo_car_racing_trained_v4")

env = gym.make("CarRacing-v3", render_mode="rgb_array")

model = PPO.load("ppo_car_racing_trained_v4", env=env)

env = DummyVecEnv([lambda: env])

images = []
obs = env.reset()
for i in range(1000):
    action, _ = model.predict(obs)
    obs, reward, done, info = env.step(action)
    images.append(env.render())
    if done:
        break

imageio.mimsave("car_racing_video_updated4.mp4", images, fps=30)


Video("car_racing_video_updated4.mp4", embed=True, width=600, height=400, html_attributes="autoplay loop")

env = gym.make("CarRacing-v3", render_mode="rgb_array")

model = PPO.load("ppo_car_racing_trained_v2", env=env)

model.learn(total_timesteps=100_000)

model.save("ppo_car_racing_trained_v4")

env = gym.make("CarRacing-v3", render_mode="rgb_array")

model = PPO.load("ppo_car_racing_trained_v3", env=env)

env = DummyVecEnv([lambda: env])

images = []
obs = env.reset()
for i in range(1000):
    action, _ = model.predict(obs)
    obs, reward, done, info = env.step(action)
    images.append(env.render())
    if done:
        break

imageio.mimsave("car_racing_video_updated4.mp4", images, fps=30)


Video("car_racing_video_updated4.mp4", embed=True, width=600, height=400, html_attributes="autoplay loop")

env = gym.make("CarRacing-v3", render_mode="rgb_array")

model = PPO.load("ppo_car_racing_trained_v4", env=env)

env = DummyVecEnv([lambda: env])

images = []
obs = env.reset()
for i in range(1000):
    action, _ = model.predict(obs)
    obs, reward, done, info = env.step(action)
    images.append(env.render())
    if done:
        break

imageio.mimsave("car_racing_video_updated_compare.mp4", images, fps=30)


Video("car_racing_video_updated_compare.mp4", embed=True, width=600, height=400, html_attributes="autoplay loop")

env = gym.make("CarRacing-v3", render_mode="rgb_array")

model = PPO.load("ppo_car_racing_trained_v2", env=env)

env = DummyVecEnv([lambda: env])
images = []
obs = env.reset()
for i in range(1000):
    action, _ = model.predict(obs)
    obs, reward, done, info = env.step(action)
    images.append(env.render())
    if done:
        break

imageio.mimsave("car_racing_video_updated_compare.mp4", images, fps=30)


Video("car_racing_video_updated_compare.mp4", embed=True, width=600, height=400, html_attributes="autoplay loop")

env = gym.make("CarRacing-v3", render_mode="rgb_array")

model = PPO.load("ppo_car_racing_trained_v4", env=env)

model.learn(total_timesteps=100_000)

model.save("ppo_car_racing_trained_v4")

env = gym.make("CarRacing-v3", render_mode="rgb_array")

model = PPO.load("ppo_car_racing_trained_v2", env=env)

env = DummyVecEnv([lambda: env])

images = []
obs = env.reset()
for i in range(1000):
    action, _ = model.predict(obs)
    obs, reward, done, info = env.step(action)
    images.append(env.render())
    if done:
        break

imageio.mimsave("car_racing_video_updated_compare2.mp4", images, fps=30)

Video("car_racing_video_updated_compare2.mp4", embed=True, width=600, height=400, html_attributes="autoplay loop")

from google.colab import files
files.download('car_racing_video_updated_compare2.mp4')

env = gym.make("CarRacing-v3", render_mode="rgb_array")

model = PPO.load("ppo_car_racing_trained_v4", env=env)

env = DummyVecEnv([lambda: env])

images = []
obs = env.reset()
for i in range(1000):
    action, _ = model.predict(obs)
    obs, reward, done, info = env.step(action)
    images.append(env.render())
    if done:
        break

imageio.mimsave("car_racing_video_updated_compare3.mp4", images, fps=30)


Video("car_racing_video_updated_compare3.mp4", embed=True, width=600, height=400, html_attributes="autoplay loop")

from google.colab import files
files.download('car_racing_video_updated_compare3.mp4')

#drive.mount('/content/drive')
model.save("/content/drive/My Drive/ppo_car_racing_trained_v4")

model.learn(total_timesteps=100_000)


model.save("ppo_car_racing_trained_v5")

env = gym.make("CarRacing-v3", render_mode="rgb_array")

model = PPO.load("ppo_car_racing_trained_v4", env=env)

env = DummyVecEnv([lambda: env])

images = []
obs = env.reset()
for i in range(1000):
    action, _ = model.predict(obs)
    obs, reward, done, info = env.step(action)
    images.append(env.render())
    if done:
        break

imageio.mimsave("car_racing_video_updated_compare4.mp4", images, fps=30)


Video("car_racing_video_updated_compare4.mp4", embed=True, width=600, height=400, html_attributes="autoplay loop")

env = gym.make("CarRacing-v3", render_mode="rgb_array")


model = PPO.load("ppo_car_racing_trained_v5", env=env)

env = DummyVecEnv([lambda: env])

images = []
obs = env.reset()
for i in range(1000):
    action, _ = model.predict(obs)
    obs, reward, done, info = env.step(action)
    images.append(env.render())
    if done:
        break

imageio.mimsave("car_racing_video_updated_compare5.mp4", images, fps=30)


Video("car_racing_video_updated_compare5.mp4", embed=True, width=600, height=400, html_attributes="autoplay loop")

!apt-get install -y xvfb swig cmake
!pip install pyvirtualdisplay
!pip install stable-baselines3==2.1.0
!pip install gymnasium[box2d] imageio
#!pip install "gymnasium[box2d]==0.29.1"
#!pip install numpy==1.26.4 --force-reinstall
#!pip install -U "gymnasium[box2d]"
#!pip install imageio

!pip install -U gymnasium stable-baselines3

!pip uninstall -y numpy
!pip install --no-cache-dir numpy

from google.colab import drive
drive.mount('/content/drive')
!cp /content/drive/MyDrive/ppo_car_racing.zip /content/drive/MyDrive/

import gymnasium as gym
from stable_baselines3 import PPO

env = gym.make("CarRacing-v3", render_mode="rgb_array")


model = PPO.load("ppo_car_racing_trained_v4", env=env)

model.learn(total_timesteps=100_000)

model.save("ppo_car_racing_trained_v4")

env = gym.make("CarRacing-v3", render_mode="rgb_array")

model = PPO.load("ppo_car_racing_trained_v4", env=env)

from stable_baselines3.common.vec_env import DummyVecEnv
import gymnasium as gym
import imageio
from IPython.display import Video

from stable_baselines3.common.vec_env import DummyVecEnv
import gymnasium as gym
from stable_baselines3 import PPO

env = gym.make("CarRacing-v3", render_mode="rgb_array")

model = PPO.load("ppo_car_racing_trained_v4", env=env)

env = DummyVecEnv([lambda: env])

images = []
obs = env.reset()
for i in range(1000):
    action, _ = model.predict(obs)
    obs, reward, done, info = env.step(action)
    images.append(env.render())
    if done:
        break

imageio.mimsave("car_racing_video_updated_compare6.mp4", images, fps=30)


Video("car_racing_video_updated_compare6.mp4", embed=True, width=600, height=400, html_attributes="autoplay loop")

from google.colab import files

files.download('car_racing_video_updated_compare6.mp4')

env = gym.make("CarRacing-v3", render_mode="rgb_array")
model = PPO.load("ppo_car_racing_trained_v4", env=env)

model.learn(total_timesteps=50000)
model.save("ppo_car_racing_trained_v5")

model.learn(total_timesteps=50000)

model.save("ppo_car_racing_trained_v5")

model.learn(total_timesteps=50000)

model.save("ppo_car_racing_trained_v5")

from stable_baselines3.common.vec_env import DummyVecEnv
import gymnasium as gym
from stable_baselines3 import PPO

env = gym.make("CarRacing-v3", render_mode="rgb_array")

model = PPO.load("ppo_car_racing_trained_v5", env=env)

env = DummyVecEnv([lambda: env])

images = []
obs = env.reset()
for i in range(1000):
    action, _ = model.predict(obs)
    obs, reward, done, info = env.step(action)
    images.append(env.render())
    if done:
        break

imageio.mimsave("car_racing_video_updated_compare7.mp4", images, fps=30)


Video("car_racing_video_updated_compare7.mp4", embed=True, width=600, height=400, html_attributes="autoplay loop")

from google.colab import files

files.download('car_racing_video_updated_compare7.mp4')

model.learn(total_timesteps=100000)

model.save("ppo_car_racing_trained_v5")

from stable_baselines3.common.vec_env import DummyVecEnv
import gymnasium as gym
from stable_baselines3 import PPO

env = gym.make("CarRacing-v3", render_mode="rgb_array")


model = PPO.load("ppo_car_racing_trained_v5", env=env)

env = DummyVecEnv([lambda: env])
images = []
obs = env.reset()
for i in range(1000):
    action, _ = model.predict(obs)
    obs, reward, done, info = env.step(action)
    images.append(env.render())
    if done:
        break

imageio.mimsave("car_racing_video_updated_compare8.mp4", images, fps=30)


Video("car_racing_video_updated_compare8.mp4", embed=True, width=600, height=400, html_attributes="autoplay loop")

from google.colab import files

files.download('car_racing_video_updated_compare8.mp4')

model.learn(total_timesteps=100000)

model.save("ppo_car_racing_trained_v5")

model.learn(total_timesteps=100000)


model.save("ppo_car_racing_trained_v5")

from stable_baselines3.common.vec_env import DummyVecEnv
import gymnasium as gym
from stable_baselines3 import PPO

env = gym.make("CarRacing-v3", render_mode="rgb_array")


model = PPO.load("ppo_car_racing_trained_v5", env=env)

env = DummyVecEnv([lambda: env])

images = []
obs = env.reset()
for i in range(1000):
    action, _ = model.predict(obs)
    obs, reward, done, info = env.step(action)
    images.append(env.render())
    if done:
        break

imageio.mimsave("car_racing_video_updated_compare9.mp4", images, fps=30)


Video("car_racing_video_updated_compare9.mp4", embed=True, width=600, height=400, html_attributes="autoplay loop")

state = env.unwrapped

print(state)

from google.colab import files

files.download('car_racing_video_updated_compare9.mp4')

model.learn(total_timesteps=100000)


model.save("ppo_car_racing_trained_v5")

from stable_baselines3.common.vec_env import DummyVecEnv
import gymnasium as gym
from stable_baselines3 import PPO

env = gym.make("CarRacing-v3", render_mode="rgb_array")


model = PPO.load("ppo_car_racing_trained_v5", env=env)

env = DummyVecEnv([lambda: env])

images = []
obs = env.reset()
for i in range(1000):
    action, _ = model.predict(obs)
    obs, reward, done, info = env.step(action)
    images.append(env.render())
    if done:
        break

imageio.mimsave("car_racing_video_updated_compare10.mp4", images, fps=30)


Video("car_racing_video_updated_compare10.mp4", embed=True, width=600, height=400, html_attributes="autoplay loop")

model.learn(total_timesteps=50_000)


model.save("ppo_car_racing_trained_v5")

from stable_baselines3.common.vec_env import DummyVecEnv
import gymnasium as gym
from stable_baselines3 import PPO

env = gym.make("CarRacing-v3", render_mode="rgb_array")


model = PPO.load("ppo_car_racing_trained_v5", env=env)

env = DummyVecEnv([lambda: env])

images = []
obs = env.reset()
for i in range(1000):
    action, _ = model.predict(obs)
    obs, reward, done, info = env.step(action)
    images.append(env.render())
    if done:
        break

imageio.mimsave("car_racing_video_updated_compare10.mp4", images, fps=30)


Video("car_racing_video_updated_compare10.mp4", embed=True, width=600, height=400, html_attributes="autoplay loop")

!apt-get install -y xvfb swig cmake
!pip install pyvirtualdisplay
!pip install stable-baselines3==2.1.0
!pip install gymnasium[box2d] imageio
#!pip install "gymnasium[box2d]==0.29.1"
#!pip install numpy==1.26.4 --force-reinstall
#!pip install -U "gymnasium[box2d]"
#!pip install imageio

!pip install -U gymnasium stable-baselines3

!pip uninstall -y numpy
!pip install --no-cache-dir numpy

import gymnasium as gym
from stable_baselines3 import PPO

env = gym.make("CarRacing-v3", render_mode="rgb_array")


model = PPO.load("ppo_car_racing_trained_v5", env=env)

model.learn(total_timesteps=50_000)

model.save("ppo_car_racing_trained_v5")

import imageio
from IPython.display import Video

from stable_baselines3.common.vec_env import DummyVecEnv
import gymnasium as gym
from stable_baselines3 import PPO

env = gym.make("CarRacing-v3", render_mode="rgb_array")


model = PPO.load("ppo_car_racing_trained_v5", env=env)

env = DummyVecEnv([lambda: env])

images = []
obs = env.reset()
for i in range(1000):
    action, _ = model.predict(obs)
    obs, reward, done, info = env.step(action)
    images.append(env.render())
    if done:
        break

imageio.mimsave("car_racing_video_updated_compare10.mp4", images, fps=30)


Video("car_racing_video_updated_compare10.mp4", embed=True, width=600, height=400, html_attributes="autoplay loop")

model.learn(total_timesteps=50_000)

model.save("ppo_car_racing_trained_v5")

import imageio
from IPython.display import Video

from stable_baselines3.common.vec_env import DummyVecEnv
import gymnasium as gym
from stable_baselines3 import PPO

env = gym.make("CarRacing-v3", render_mode="rgb_array")


model = PPO.load("ppo_car_racing_trained_v5", env=env)

env = DummyVecEnv([lambda: env])

images = []
obs = env.reset()
for i in range(1000):
    action, _ = model.predict(obs)
    obs, reward, done, info = env.step(action)
    images.append(env.render())
    if done:
        break

imageio.mimsave("car_racing_video_updated_compare10.mp4", images, fps=30)


Video("car_racing_video_updated_compare10.mp4", embed=True, width=600, height=400, html_attributes="autoplay loop")

from stable_baselines3.common.vec_env import DummyVecEnv
import gymnasium as gym
import imageio
from IPython.display import Video


env = gym.make("CarRacing-v3", render_mode="rgb_array")

model = PPO.load("ppo_car_racing_trained_v5", env=env)


env = DummyVecEnv([lambda: env])


images = []
obs = env.reset()
for i in range(1000):
    action, _ = model.predict(obs)
    obs, reward, done, info = env.step(action)
    images.append(env.render())
    if done:

        obs = env.reset()

imageio.mimsave("car_racing_extended_video_extra.mp4", images, fps=30)


Video("car_racing_extended_video_extra.mp4", embed=True, width=600, height=400, html_attributes="autoplay loop")

from google.colab import files

files.download('car_racing_video_updated_compare10.mp4')

model.learn(total_timesteps=100000)

model.save("ppo_car_racing_trained_v5")

from stable_baselines3.common.vec_env import DummyVecEnv
import gymnasium as gym
from stable_baselines3 import PPO

env = gym.make("CarRacing-v3", render_mode="rgb_array")


model = PPO.load("ppo_car_racing_trained_v5", env=env)

env = DummyVecEnv([lambda: env])

images = []
obs = env.reset()
for i in range(1000):
    action, _ = model.predict(obs)
    obs, reward, done, info = env.step(action)
    images.append(env.render())
    if done:
        break

imageio.mimsave("car_racing_video_updated_compare11.mp4", images, fps=30)

Video("car_racing_video_updated_compare11.mp4", embed=True, width=600, height=400, html_attributes="autoplay loop")

files.download('car_racing_video_updated_compare10.mp4')

model.learn(total_timesteps=100000)

model.save("ppo_car_racing_trained_v5")

from stable_baselines3.common.vec_env import DummyVecEnv
import gymnasium as gym
import imageio
from IPython.display import Video


env = gym.make("CarRacing-v3", render_mode="rgb_array")


model = PPO.load("ppo_car_racing_trained_v5", env=env)


env = DummyVecEnv([lambda: env])


images = []
obs = env.reset()
for i in range(1000):
    action, _ = model.predict(obs)
    obs, reward, done, info = env.step(action)
    images.append(env.render())
    if done:

        obs = env.reset()

imageio.mimsave("car_racing_extended_video_extra.mp4", images, fps=30)


Video("car_racing_extended_video_extra.mp4", embed=True, width=600, height=400, html_attributes="autoplay loop")

files.download('car_racing_extended_video_extra.mp4')

model.learn(total_timesteps=100000)


model.save("ppo_car_racing_trained_v5")

from stable_baselines3.common.vec_env import DummyVecEnv
import gymnasium as gym
from stable_baselines3 import PPO

env = gym.make("CarRacing-v3", render_mode="rgb_array")


model = PPO.load("ppo_car_racing_trained_v5", env=env)

env = DummyVecEnv([lambda: env])

images = []
obs = env.reset()
for i in range(1000):
    action, _ = model.predict(obs)
    obs, reward, done, info = env.step(action)
    images.append(env.render())
    if done:
        break

imageio.mimsave("car_racing_video_updated_compare12.mp4", images, fps=30)


Video("car_racing_video_updated_compare12.mp4", embed=True, width=600, height=400, html_attributes="autoplay loop")

model.learn(total_timesteps=200000)

model.save("ppo_car_racing_trained_v5")

from stable_baselines3.common.vec_env import DummyVecEnv
import gymnasium as gym
from stable_baselines3 import PPO

env = gym.make("CarRacing-v3", render_mode="rgb_array")

model = PPO.load("ppo_car_racing_trained_v5", env=env)

env = DummyVecEnv([lambda: env])

images = []
obs = env.reset()
for i in range(1000):
    action, _ = model.predict(obs)
    obs, reward, done, info = env.step(action)
    images.append(env.render())
    if done:
        break

imageio.mimsave("car_racing_video_updated_compare13.mp4", images, fps=30)


Video("car_racing_video_updated_compare13.mp4", embed=True, width=600, height=400, html_attributes="autoplay loop")

files.download('car_racing_video_updated_compare13.mp4')

model.learn(total_timesteps=100000)

model.save("ppo_car_racing_trained_v5")

from stable_baselines3.common.vec_env import DummyVecEnv
import gymnasium as gym
from stable_baselines3 import PPO

env = gym.make("CarRacing-v3", render_mode="rgb_array")


model = PPO.load("ppo_car_racing_trained_v5", env=env)

env = DummyVecEnv([lambda: env])

images = []
obs = env.reset()
for i in range(1000):
    action, _ = model.predict(obs)
    obs, reward, done, info = env.step(action)
    images.append(env.render())
    if done:
        break

imageio.mimsave("car_racing_video_updated_compare14.mp4", images, fps=30)

Video("car_racing_video_updated_compare14.mp4", embed=True, width=600, height=400, html_attributes="autoplay loop")



from stable_baselines3.common.evaluation import evaluate_policy
import gymnasium as gym
from stable_baselines3 import PPO


env = gym.make("CarRacing-v3", render_mode="rgb_array")


model = PPO.load("ppo_car_racing_trained_v5", env=env)

mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=10)


print(f"Mean reward: {mean_reward}, Standard deviation: {std_reward}")

model.save("ppo_car_racing_trained_v6")

from google.colab import drive
drive.mount('/content/drive')

model.save("/content/drive/MyDrive/ppo_car_racing_trained_v6")

from stable_baselines3.common.monitor import Monitor
from stable_baselines3.common.evaluation import evaluate_policy
import gymnasium as gym
from stable_baselines3 import PPO


env = gym.make("CarRacing-v3", render_mode="rgb_array")


env = Monitor(env, filename="evaluation_results")


model = PPO.load("ppo_car_racing_trained_v5", env=env)


mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=10)


print(f"Mean reward: {mean_reward}, Standard deviation: {std_reward}")
print(f"Mean reward: {mean_reward}, Standard deviation: {std_reward}")

model.learn(total_timesteps=100000)


model.save("ppo_car_racing_trained_v5")

from stable_baselines3.common.vec_env import DummyVecEnv
import gymnasium as gym
from stable_baselines3 import PPO

env = gym.make("CarRacing-v3", render_mode="rgb_array")


model = PPO.load("ppo_car_racing_trained_v5", env=env)

env = DummyVecEnv([lambda: env])

images = []
obs = env.reset()
for i in range(1000):
    action, _ = model.predict(obs)
    obs, reward, done, info = env.step(action)
    images.append(env.render())
    if done:
        break

imageio.mimsave("car_racing_video_updated_compare13.mp4", images, fps=30)


Video("car_racing_video_updated_compare13.mp4", embed=True, width=600, height=400, html_attributes="autoplay loop")

files.download('car_racing_video_updated_compare13.mp4')

model.learn(total_timesteps=100000)

model.save("ppo_car_racing_trained_v5")

from google.colab import drive
drive.mount('/content/drive')

model.save("/content/drive/MyDrive/ppo_car_racing_trained_v5")

!apt-get install -y xvfb swig cmake
!pip install pyvirtualdisplay
!pip install stable-baselines3==2.1.0
!pip install gymnasium[box2d] imageio
#!pip install "gymnasium[box2d]==0.29.1"
#!pip install numpy==1.26.4 --force-reinstall
#!pip install -U "gymnasium[box2d]"
#!pip install imageio

!pip install -U gymnasium stable-baselines3

!pip uninstall -y numpy
!pip install --no-cache-dir numpy

import gymnasium as gym
from stable_baselines3 import PPO

env = gym.make("CarRacing-v3", render_mode="rgb_array")


model = PPO.load("ppo_car_racing_trained_v7", env=env)

import torch
print("CUDA available:", torch.cuda.is_available())

model = PPO("CnnPolicy", env, verbose=1, device="cuda")

import torch
print("CUDA available:", torch.cuda.is_available())
print("Device being used:", torch.device("cuda" if torch.cuda.is_available() else "cpu"))

import gymnasium as gym
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv


env = DummyVecEnv([lambda: gym.make("CarRacing-v3", render_mode="rgb_array")] * 4)


model = PPO("CnnPolicy", env, verbose=1)


model.learn(total_timesteps=100000)

from stable_baselines3.common.vec_env import DummyVecEnv
import gymnasium as gym
from stable_baselines3 import PPO

env = gym.make("CarRacing-v3", render_mode="rgb_array")


model = PPO.load("ppo_car_racing_trained_v7", env=env)

env = DummyVecEnv([lambda: env])

images = []
obs = env.reset()
for i in range(1000):
    action, _ = model.predict(obs)
    obs, reward, done, info = env.step(action)
    images.append(env.render())
    if done:
        break

imageio.mimsave("car_racing_video_updated_compare2.mp4", images, fps=30)

Video("car_racing_video_updated_compare2.mp4", embed=True, width=600, height=400, html_attributes="autoplay loop")



import gymnasium as gym
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv, VecTransposeImage
from stable_baselines3.common.callbacks import CheckpointCallback


MODEL_PATH = "/content/drive/MyDrive/ppo_car_racing_trained_v7"
CHECKPOINT_DIR = "/content/drive/MyDrive/ppo_checkpoints/"


env = DummyVecEnv([lambda: gym.make("CarRacing-v3", render_mode="rgb_array")])
env = VecTransposeImage(env)


try:
    model = PPO.load(MODEL_PATH, env=env)
    print("✅ Loaded existing model.")
except:
    model = PPO("CnnPolicy", env, verbose=1, tensorboard_log="./ppo_tensorboard/")
    print("🔄 No existing model found, starting from scratch.")

checkpoint_callback = CheckpointCallback(
    save_freq=250_000,
    save_path=CHECKPOINT_DIR,
    name_prefix="ppo_carracing"
)


model.learn(total_timesteps=1_000_000, callback=checkpoint_callback)

model.save(MODEL_PATH)
print("📦 Final model saved at:", MODEL_PATH)

from google.colab import drive
drive.mount('/content/drive')

model.save("/content/drive/MyDrive/ppo_car_racing_trained_v6")

from stable_baselines3.common.vec_env import DummyVecEnv  # Import DummyVecEnv
import gymnasium as gym
from stable_baselines3 import PPO

import imageio
from IPython.display import Video

env = gym.make("CarRacing-v3", render_mode="rgb_array")
model = PPO.load("ppo_car_racing_trained_v5", env=env)

# 1. Install Dependencies (if not already installed)
#!pip install stable-baselines3[extra] gymnasium[box2d] --quiet

# 2. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

import gymnasium as gym
from stable_baselines3 import PPO

# Create the environment
env = gym.make("CarRacing-v3", render_mode="rgb_array")

# Specify the checkpoint path (adjust if needed)
checkpoint_path = "/content/drive/MyDrive/ppo_checkpoints/ppo_carracing_750000_steps.zip"

# Load the model
model = PPO.load(checkpoint_path, env=env)

print("✅ Checkpoint loaded successfully!")

model.learn(total_timesteps=250000)  # Adjust the number of timesteps as needed

# Save the updated model
model.save("ppo_car_racing_trained_v7")
print("✅ Training completed and model saved!")



from stable_baselines3.common.vec_env import DummyVecEnv
import gymnasium as gym
from stable_baselines3 import PPO

env = gym.make("CarRacing-v3", render_mode="rgb_array")


model = PPO.load("ppo_car_racing_trained_v7", env=env)

env = DummyVecEnv([lambda: env])

images = []
obs = env.reset()
for i in range(1000):
    action, _ = model.predict(obs)
    obs, reward, done, info = env.step(action)
    images.append(env.render())
    if done:
        break

imageio.mimsave("car_racing_video_updated_comparetes.mp4", images, fps=30)


Video("car_racing_video_updated_comparetes.mp4", embed=True, width=600, height=400, html_attributes="autoplay loop")

import imageio
from IPython.display import Video

from IPython.display import clear_output
clear_output(wait=True)

env_car_racing = gym.make("CarRacing-v3", render_mode="rgb_array")
env = DummyVecEnv([lambda: env_car_racing])

model = PPO.load("ppo_car_racing_trained_v7.zip", env=env_car_racing)

from google.colab import drive
drive.mount('/content/drive')

!cp /content/ppo_car_racing_trained_v7.zip /content/drive/MyDrive/ppo_car_racing_trained_v7t2.zip



import gymnasium as gym
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
import imageio
from IPython.display import Video


model.save("/content/drive/MyDrive/ppo_car_racing_trained_final")
print("✅ Model saved!")


env = gym.make("CarRacing-v3", render_mode="rgb_array")
env = DummyVecEnv([lambda: env])


images = []
obs = env.reset()
for i in range(1000):
    action, _ = model.predict(obs)
    obs, reward, done, info = env.step(action)
    images.append(env.render())
    if done:
        obs = env.reset()

imageio.mimsave("car_racing_final_video.mp4", images, fps=30)
print("✅ Video saved!")


Video("car_racing_final_video.mp4", embed=True, width=600, height=400, html_attributes="autoplay loop")

model.learn(total_timesteps=100_000)

model.save("/content/drive/MyDrive/ppo_car_racing_trained_v8")
print("✅ Model saved after resuming training!")

import os
import gymnasium as gym
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy
import imageio
from IPython.display import Video


CHECKPOINT_DIR = "/content/drive/MyDrive/ppo_checkpoints"
best_reward = -float("inf")
best_checkpoint_path = None

for checkpoint_file in os.listdir(CHECKPOINT_DIR):
    if checkpoint_file.startswith("ppo_carracing"):
        checkpoint_path = os.path.join(CHECKPOINT_DIR, checkpoint_file)
        model = PPO.load(checkpoint_path)
        mean_reward, _ = evaluate_policy(model, env, n_eval_episodes=5)
        if mean_reward > best_reward:
            best_reward = mean_reward
            best_checkpoint_path = checkpoint_path

print(f"Best checkpoint: {best_checkpoint_path} (Mean reward: {best_reward})")

env = gym.make("CarRacing-v3", render_mode="rgb_array")
best_model = PPO.load(best_checkpoint_path, env=env)


env = DummyVecEnv([lambda: env])
images = []
obs = env.reset()
for i in range(1000):
    action, _ = best_model.predict(obs)
    obs, reward, done, info = env.step(action)
    images.append(env.render())
    if done:
        obs = env.reset()

imageio.mimsave("car_racing_best_checkpoint_video.mp4", images, fps=30)


Video("car_racing_best_checkpoint_video.mp4", embed=True, width=600, height=400, html_attributes="autoplay loop")

import gymnasium as gym
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
import matplotlib.pyplot as plt
from IPython import display
import time

env_for_loading = gym.make("CarRacing-v3", render_mode="rgb_array")
env_car_racing = gym.make("CarRacing-v3", render_mode="rgb_array")
eval_env = DummyVecEnv([lambda: env_car_racing])


model = PPO.load("ppo_car_racing_trained_v7.zip", env=env_for_loading)
print("✅ Loaded existing model.")


laps_completed = 0
obs = eval_env.reset()



for i in range(1000):
    action, _ = model.predict(obs, deterministic=True)
    obs, reward, done, info = eval_env.step(action)


    reward = reward[0]
    done = done[0]
    info = info[0]
    truncated = info.get("TimeLimit.truncated", False)


    if truncated:
        laps_completed += 1
        print(f"Lap completed! Total laps: {laps_completed}")


print(f"Total laps completed during evaluation: {laps_completed}")

import gymnasium as gym
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
import matplotlib.pyplot as plt
from IPython import display
import imageio
import time


env_for_loading = gym.make("CarRacing-v3", render_mode="rgb_array")
env_car_racing = gym.make("CarRacing-v3", render_mode="rgb_array")
eval_env = DummyVecEnv([lambda: env_car_racing])


model = PPO.load("ppo_car_racing_trained_v7.zip", env=env_for_loading)
print("✅ Loaded existing model.")


laps_completed = 0
obs = eval_env.reset()
frames = []

for i in range(1000):
    action, _ = model.predict(obs, deterministic=True)
    obs, reward, done, info = eval_env.step(action)


    reward = reward[0]
    done = done[0]
    info = info[0]
    truncated = info.get("TimeLimit.truncated", False)


    if truncated:
        laps_completed += 1
        print(f"Lap completed! Total laps: {laps_completed}")


    display.clear_output(wait=True)
    display.display(plt.gcf())
    plt.imshow(eval_env.render()[0])
    plt.axis('off')


    frames.append(eval_env.render()[0])

    plt.close()

    if type(plt.isinteractive()) is bool:
        if plt.isinteractive():
            plt.pause(0.01)
    else:
        plt.pause(0.01)
c

!apt-get install -y xvfb swig cmake
!pip install pyvirtualdisplay
!pip install stable-baselines3==2.1.0
!pip install gymnasium[box2d] imageio
#!pip install "gymnasium[box2d]==0.29.1"
#!pip install numpy==1.26.4 --force-reinstall
#!pip install -U "gymnasium[box2d]"
#!pip install imageio

!pip install -U gymnasium stable-baselines3

!pip uninstall -y numpy
!pip install --no-cache-dir numpy

import gymnasium as gym
from stable_baselines3 import PPO

from google.colab import drive
drive.mount('/content/drive')

env = gym.make("CarRacing-v3", render_mode="rgb_array")

model = PPO.load("ppo_carracing_750000_steps", env=env)

# env = gym.make("CarRacing-v3", render_mode="rgb_array")
# model = PPO.load("ppo_car_racing_trained_v7", env=env)


model.learn(total_timesteps=250000)

model.save("ppo_car_racing_trained_v8")

import imageio
from IPython.display import Video

import gymnasium as gym
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
import imageio
from IPython.display import Video


env = gym.make("CarRacing-v3", render_mode="rgb_array")
model = PPO.load("ppo_car_racing_trained_v8", env=env)


env = DummyVecEnv([lambda: env])

images = []
obs = env.reset()
for i in range(1000):
    action, _ = model.predict(obs)
    obs, reward, done, info = env.step(action)
    images.append(env.render())
    if done:
        break


imageio.mimsave("car_racing_video15.mp4", images, fps=30)


Video("car_racing_video15.mp4", embed=True, width=600, height=400, html_attributes="autoplay loop")

from google.colab import files

files.download('car_racing_video15.mp4')

from stable_baselines3.common.monitor import Monitor
model = PPO.load("ppo_car_racing_trained_v8", env=env.envs[0])

import pandas as pd
import matplotlib.pyplot as plt
from stable_baselines3.common.monitor import Monitor
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
import gymnasium as gym
import os

env = gym.make("CarRacing-v3", render_mode="rgb_array")
env = DummyVecEnv([lambda: env])


monitor_file = "monitor.csv"
env.envs[0] = Monitor(env.envs[0], filename=monitor_file)


model = PPO.load("ppo_car_racing_trained_v8", env=env.envs[0])

import pandas as pd
import matplotlib.pyplot as plt


df = pd.read_csv("monitor.csv", skiprows=1)


plt.figure(figsize=(10, 6))
plt.plot(df['l'], df['r'])
plt.xlabel('Timesteps')
plt.ylabel('Reward')
plt.title('Model Performance (Reward over Time)')
plt.grid(True)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt


df = pd.read_csv("monitor.csv", skiprows=1)


plt.figure(figsize=(10, 6))
plt.plot(df['l'], df['r'])
plt.xlabel('Timesteps')
plt.ylabel('Reward')
plt.title('Model Performance (Reward over Time)')
plt.grid(True)
plt.show()

monitor_data = pd.read_csv("monitor.csv")


print(monitor_data.head())


print(monitor_data.columns)

with open("monitor.csv", 'r') as file:

    for i in range(20):
        print(file.readline())

import pandas as pd


monitor_data = pd.read_csv("monitor.csv", skiprows=1)


print(monitor_data.head())

model = PPO.load("ppo_car_racing_trained_v8", env=env)

model.learn(total_timesteps=250000)


model.save("ppo_car_racing_trained_v8")

import gymnasium as gym
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
import imageio
from IPython.display import Video


env = gym.make("CarRacing-v3", render_mode="rgb_array")
model = PPO.load("ppo_car_racing_trained_v7", env=env)


env = DummyVecEnv([lambda: env])

images = []
obs = env.reset()
for i in range(1000):
    action, _ = model.predict(obs)
    obs, reward, done, info = env.step(action)
    images.append(env.render())
    if done:
        break


imageio.mimsave("car_racing_video_v7.mp4", images, fps=30)


Video("car_racing_video_v7.mp4", embed=True, width=600, height=400, html_attributes="autoplay loop")

import gymnasium as gym
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
import imageio
from IPython.display import Video

env = gym.make("CarRacing-v3", render_mode="rgb_array")
model = PPO.load("ppo_car_racing_trained_v7", env=env)


env = DummyVecEnv([lambda: env])


images = []
obs = env.reset()
for i in range(1000):
    action, _ = model.predict(obs)
    obs, reward, done, info = env.step(action)
    images.append(env.render())
    if done:
        break


imageio.mimsave("car_racing_video_v7.mp4", images, fps=30)


Video("car_racing_video_v7.mp4", embed=True, width=600, height=400, html_attributes="autoplay loop")

from google.colab import files

files.download('car_racing_video_v7.mp4')

model = PPO.load("ppo_car_racing_trained_v8", env=env)

model.learn(total_timesteps=250000)


model.save("ppo_car_racing_trained_v8")

c

env = DummyVecEnv([lambda: env])


images = []
obs = env.reset()
for i in range(1000):
    action, _ = model.predict(obs)
    obs, reward, done, info = env.step(action)
    images.append(env.render())
    if done:
        break


imageio.mimsave("car_racing_video_v8.mp4", images, fps=30)

Video("car_racing_video_v8.mp4", embed=True, width=600, height=400, html_attributes="autoplay loop")

from google.colab import files

files.download('car_racing_video_v8.mp4')

import gymnasium as gym
from stable_baselines3 import A2C

env = gym.make("CarRacing-v3", render_mode="rgb_array")
model = A2C("CnnPolicy", env, verbose=1)
model.learn(total_timesteps=100000)

import gymnasium as gym
import numpy as np

class CustomRewardWrapper(gym.Wrapper):
    def __init__(self, env):
        super().__init__(env)
        self.prev_position = None

    def reset(self, **kwargs):
        obs, info = self.env.reset(**kwargs)
        self.prev_position = self.car_position(obs)
        return obs, info

    def step(self, action):
        obs, reward, terminated, truncated, info = self.env.step(action)


        current_position = self.car_position(obs)
        reward = self.calculate_reward(current_position)

        self.prev_position = current_position
        return obs, reward, terminated, truncated, info

    def car_position(self, obs):

        height, width, _ = obs.shape
        return (width // 2, height - 10)

    def calculate_reward(self, current_position):

        distance_traveled = current_position[1] - self.prev_position[1]
        reward = distance_traveled

        return reward

env = gym.make("CarRacing-v3", render_mode="rgb_array")

env = CustomRewardWrapper(env)


model = PPO.load("ppo_carracing_750000_steps", env=env)

model.learn(total_timesteps=100000)


model.save("ppo_carracing_updated")

import gymnasium as gym
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
import imageio
from IPython.display import Video


#env = gym.make("CarRacing-v3", render_mode="rgb_array")
#model = PPO.load("ppo_car_racing_trained_v8", env=env)
env = DummyVecEnv([lambda: env])


images = []
obs = env.reset()
for i in range(1000):
    action, _ = model.predict(obs)
    obs, reward, done, info = env.step(action)
    images.append(env.render())
    if done:
        break


imageio.mimsave("car_racing_video_v19.mp4", images, fps=30)

Video("car_racing_video_v19.mp4", embed=True, width=600, height=400, html_attributes="autoplay loop")

from google.colab import files

files.download('car_racing_video_v19.mp4')